In [14]:
import pandas as pd
from sqlalchemy import create_engine
import urllib

In [16]:
##connection string
params = urllib.parse.quote_plus(

    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=LAPTOP-71G1NMQR\\SQLEXPRESS;"
    "DATABASE=BLINKIT_DB;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"

)

In [17]:
##engine create
engine = create_engine(

    f"mssql+pyodbc:///?odbc_connect={params}"

)

Data Load from sqlserveer CUSTOMERS_CLEAN, ORDERS_CLEAN, ORDER_ITEMS_CLEAN, PRODUCTS_CLEAN

In [18]:
customers = pd.read_sql(

    "SELECT * FROM CUSTOMERS_CLEAN",
    engine

)

In [20]:
orders = pd.read_sql(

    "SELECT * FROM ORDERS_CLEAN",
    engine

)

In [21]:
order_items = pd.read_sql(

    "SELECT * FROM ORDER_ITEMS_CLEAN",
    engine

)

In [46]:
products = pd.read_sql(

    "SELECT * FROM PRODUCTS_CLEAN",
    engine

)

           Check Data all

In [42]:
customers.info()
customers.head()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   customer_id        2500 non-null   int64  
 1   customer_name      2500 non-null   str    
 2   email              2500 non-null   str    
 3   phone              2500 non-null   str    
 4   address            2500 non-null   str    
 5   area               2500 non-null   str    
 6   pincode            2500 non-null   str    
 7   registration_date  2500 non-null   object 
 8   customer_segment   2500 non-null   str    
 9   total_orders       2500 non-null   int64  
 10  avg_order_value    2500 non-null   float64
dtypes: float64(1), int64(2), object(1), str(7)
memory usage: 215.0+ KB


,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,31813,Indrajit Pau,wakeetasehgal@example.com,+911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,2024-04-10,Regular,18,1230.75
1,31826,Ekiya Pau,fbedi@example.com,+919364120886,"H.No. 336\nLad Zila, Hajipur-409871",Chinsurah,201602,2023-11-29,New,18,752.78
2,61020,Onkar Suresh,rudradeshpande@example.com,+918421031341,"88/40, Bora Zila, Phusro-161515",Kurnool,345635,2024-07-27,New,19,1703.16
3,75482,Jeet Gandhi,amrita05@example.net,+916683687947,"95/861, Jaggi, Sikar-343285",Korba,298093,2024-09-19,Regular,13,1938.38
4,119099,Zansi Parsa,neha08@example.com,+912032907631,"H.No. 40, Gopal Ganj, Bidar 854350",Kavali,692517,2023-08-01,Inactive,20,637.35


In [43]:
orders.info()
orders.head()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   order_id                5000 non-null   int64         
 1   customer_id             5000 non-null   int64         
 2   order_date              5000 non-null   object        
 3   promised_delivery_time  5000 non-null   datetime64[us]
 4   actual_delivery_time    5000 non-null   datetime64[us]
 5   delivery_status         5000 non-null   str           
 6   order_total             5000 non-null   float64       
 7   payment_method          5000 non-null   str           
 8   delivery_partner_id     5000 non-null   int64         
 9   store_id                5000 non-null   int64         
dtypes: datetime64[us](2), float64(1), int64(4), object(1), str(2)
memory usage: 390.8+ KB


,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,60465,15808945,2024-10-23,2024-10-23 05:34:29,2024-10-23 05:39:29,On Time,589.47,UPI,58998,3943
1,2237858,48281892,2023-04-02,2023-04-02 04:00:11,2023-04-02 04:03:11,On Time,3835.26,Wallet,97945,1987
2,3101265,89617089,2024-05-23,2024-05-23 03:37:47,2024-05-23 03:40:47,On Time,3567.73,UPI,20246,974
3,5120698,44174426,2023-06-09,2023-06-09 12:25:20,2023-06-09 12:40:20,Slightly Delayed,3064.36,Wallet,48582,3184
4,5512907,51476157,2023-04-30,2023-04-30 21:11:21,2023-04-30 21:26:21,Slightly Delayed,861.53,Wallet,44545,419


In [44]:
order_items.info()
order_items.head()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   order_id    5000 non-null   int64  
 1   product_id  5000 non-null   int64  
 2   quantity    5000 non-null   int64  
 3   unit_price  5000 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 156.4 KB


,order_id,product_id,quantity,unit_price
0,1961864118,642612,3,517.03
1,1549769649,378676,1,881.42
2,9185164487,741341,2,923.84
3,9644738826,561860,1,874.78
4,5427684290,602241,2,976.55


In [47]:
products.info()
products.head()

<class 'pandas.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   product_id         268 non-null    int64  
 1   product_name       268 non-null    str    
 2   category           268 non-null    str    
 3   brand              268 non-null    str    
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64  
 8   min_stock_level    268 non-null    int64  
 9   max_stock_level    268 non-null    int64  
dtypes: float64(3), int64(4), str(3)
memory usage: 21.1 KB


,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,4452,Baby Wipes,Baby Care,Morar-Mistry,169.88,242.69,30.0,365,27,100
1,6405,Baby Food,Baby Care,Kashyap-Reddy,236.51,337.87,30.0,365,11,81
2,9436,Toothpaste,Personal Care,Naidu PLC,88.43,136.05,35.0,365,19,76
3,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
4,14145,Spinach,Fruits & Vegetables,"Thakur, Shah and Pingle",630.84,841.12,25.0,3,14,53


                     1. CUSTOMERS_CLEAN EDA

In [57]:
# First 5 Rows
customers.head()

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,31813,Indrajit Pau,wakeetasehgal@example.com,+911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,2024-04-10,Regular,18,1230.75
1,31826,Ekiya Pau,fbedi@example.com,+919364120886,"H.No. 336\nLad Zila, Hajipur-409871",Chinsurah,201602,2023-11-29,New,18,752.78
2,61020,Onkar Suresh,rudradeshpande@example.com,+918421031341,"88/40, Bora Zila, Phusro-161515",Kurnool,345635,2024-07-27,New,19,1703.16
3,75482,Jeet Gandhi,amrita05@example.net,+916683687947,"95/861, Jaggi, Sikar-343285",Korba,298093,2024-09-19,Regular,13,1938.38
4,119099,Zansi Parsa,neha08@example.com,+912032907631,"H.No. 40, Gopal Ganj, Bidar 854350",Kavali,692517,2023-08-01,Inactive,20,637.35


In [67]:
# Statistical Summary
customers.describe(include="number").round(2)


,customer_id,total_orders,avg_order_value
count,2500.00,2500.00,2500.00
mean,49899613.22,10.49,1102.38
std,29192657.93,5.81,523.04
min,31813.00,1.00,200.43
25%,24024434.00,6.00,631.82
50%,50000439.50,10.00,1118.65
75%,75954591.75,16.00,1565.40
max,99893898.00,20.00,1999.83


In [69]:
# Total Customers = 2500
customers["customer_id"].nunique()

2500

In [70]:
# Customer Segment Distribution
customers["customer_segment"].value_counts()

customer_segment
Regular     639
Premium     633
New         628
Inactive    600
Name: count, dtype: int64

In [71]:
# Top 10 Areas
customers["area"].value_counts().head(10)

area
Jalna          18
Bathinda       17
Orai           17
Deoghar        17
Ghaziabad      16
Ratlam         16
Kishanganj     15
Gandhinagar    14
Kadapa         14
Nandyal        14
Name: count, dtype: int64

In [77]:
##registrartion date column convert datetime
customers["registration_date"]= pd.to_datetime(customers["registration_date"],
                                               errors= "coerce")

In [78]:
customers["registration_date"].dtype

dtype('<M8[s]')

In [80]:
# Registration Date Analysis
customers["registration_date"].min()

Timestamp('2023-03-16 00:00:00')

In [81]:

customers["registration_date"].max()

Timestamp('2024-11-04 00:00:00')

               2. ORDERS_CLEAN EDA

In [82]:
# First 5 Rows
orders.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,60465,15808945,2024-10-23,2024-10-23 05:34:29,2024-10-23 05:39:29,On Time,589.47,UPI,58998,3943
1,2237858,48281892,2023-04-02,2023-04-02 04:00:11,2023-04-02 04:03:11,On Time,3835.26,Wallet,97945,1987
2,3101265,89617089,2024-05-23,2024-05-23 03:37:47,2024-05-23 03:40:47,On Time,3567.73,UPI,20246,974
3,5120698,44174426,2023-06-09,2023-06-09 12:25:20,2023-06-09 12:40:20,Slightly Delayed,3064.36,Wallet,48582,3184
4,5512907,51476157,2023-04-30,2023-04-30 21:11:21,2023-04-30 21:26:21,Slightly Delayed,861.53,Wallet,44545,419


In [91]:
# Statistical Summary
orders["order_total"].describe().round(2)


count    5000.00
mean     2201.86
std      1303.02
min        13.25
25%      1086.21
50%      2100.69
75%      3156.88
max      6721.46
Name: order_total, dtype: float64

In [92]:
# Order Date Analysis
orders["order_date"].min()

datetime.date(2023, 3, 16)

In [93]:
orders["order_date"].max()

datetime.date(2024, 11, 4)

In [94]:
# Delivery Partner Analysis
orders["delivery_partner_id"].nunique()

5000

In [95]:
# Store Analysis
orders["store_id"].nunique()

5000

                3. ORDER_ITEMS_CLEAN EDA

In [96]:
# First 5 Rows
order_items.head()

,order_id,product_id,quantity,unit_price
0,1961864118,642612,3,517.03
1,1549769649,378676,1,881.42
2,9185164487,741341,2,923.84
3,9644738826,561860,1,874.78
4,5427684290,602241,2,976.55


In [97]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   order_id    5000 non-null   int64  
 1   product_id  5000 non-null   int64  
 2   quantity    5000 non-null   int64  
 3   unit_price  5000 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 156.4 KB


In [102]:
# Statistical Summary
order_items["quantity"].describe()

count    5000.000000
mean        2.006800
std         0.820542
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max         3.000000
Name: quantity, dtype: float64

In [103]:
order_items["unit_price"].describe()

count    5000.000000
mean      493.157900
std       298.075647
min        12.320000
25%       227.220000
50%       448.160000
75%       781.080000
max       995.980000
Name: unit_price, dtype: float64

In [104]:
# Top Selling Products
order_items["product_id"].value_counts().head(10)


product_id
51036     34
820973    33
34186     29
992178    29
880510    29
131748    29
604184    28
89084     28
654623    28
451812    27
Name: count, dtype: int64

In [105]:
# Quantity Distribution
order_items["quantity"].value_counts()

quantity
3    1700
1    1666
2    1634
Name: count, dtype: int64

            4. PRODUCTS_CLEAN EDA

In [106]:
# Information
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   product_id         268 non-null    int64  
 1   product_name       268 non-null    str    
 2   category           268 non-null    str    
 3   brand              268 non-null    str    
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64  
 8   min_stock_level    268 non-null    int64  
 9   max_stock_level    268 non-null    int64  
dtypes: float64(3), int64(4), str(3)
memory usage: 21.1 KB


In [109]:
products.head()

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,4452,Baby Wipes,Baby Care,Morar-Mistry,169.88,242.69,30.0,365,27,100
1,6405,Baby Food,Baby Care,Kashyap-Reddy,236.51,337.87,30.0,365,11,81
2,9436,Toothpaste,Personal Care,Naidu PLC,88.43,136.05,35.0,365,19,76
3,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
4,14145,Spinach,Fruits & Vegetables,"Thakur, Shah and Pingle",630.84,841.12,25.0,3,14,53


In [112]:
# Total Products = 268
products["product_id"].nunique()

268

In [114]:
products.describe(include="number").round(2)

,product_id,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
count,268.00,268.00,268.00,268.00,268.00,268.00,268.00
mean,514855.94,488.36,680.43,27.78,231.76,20.39,74.75
std,291391.53,298.49,419.77,7.46,151.21,5.96,14.59
min,4452.00,12.32,17.60,15.00,3.00,10.00,50.00
25%,273697.75,226.72,325.15,20.00,90.00,15.00,63.75
50%,541459.00,442.18,616.97,30.00,365.00,21.00,73.00
75%,754334.00,779.44,1056.62,35.00,365.00,25.25,88.00
max,993331.00,995.98,1633.32,40.00,365.00,30.00,100.00


In [116]:
# Categories Count
products["category"].value_counts()


category
Dairy & Breakfast        30
Fruits & Vegetables      27
Household Care           27
Snacks & Munchies        27
Personal Care            25
Pharmacy                 25
Pet Care                 25
Grocery & Staples        24
Cold Drinks & Juices     22
Instant & Frozen Food    20
Baby Care                16
Name: count, dtype: int64

In [117]:
# Top 10 Brands
products["brand"].value_counts().head(10)

brand
Jha Group                  2
Morar-Mistry               1
Kashyap-Reddy              1
Naidu PLC                  1
Ramaswamy-Tata             1
Thakur, Shah and Pingle    1
Banik-Ratta                1
Ramesh Inc                 1
Shah and Sons              1
Gaba LLC                   1
Name: count, dtype: int64

In [122]:
##Category Wise Average Price
products.groupby("category")[
    "price"
].mean().sort_values(
    ascending=False
).round(2)

category
Pharmacy                 599.03
Dairy & Breakfast        569.10
Pet Care                 546.93
Fruits & Vegetables      546.54
Baby Care                516.15
Cold Drinks & Juices     500.52
Personal Care            441.60
Instant & Frozen Food    420.34
Snacks & Munchies        417.11
Household Care           403.19
Grocery & Staples        397.36
Name: price, dtype: float64

In [123]:
##Brand Wise Price
products.groupby("brand")[
    "price"
].mean().sort_values(
    ascending=False
).head(10)

brand
Gole-Doshi                995.98
Gera, Narang and Karpe    994.56
Chahal Group              989.88
Mammen-Hegde              979.99
Bahl-Pau                  976.55
Banerjee Inc              973.44
Dutta-Halder              972.69
Ramesh Inc                968.94
Dutta Inc                 959.01
Roy-Char                  951.43
Name: price, dtype: float64

                           One Table by Merge  for Better EDA 

In [126]:
# Step-1 : Customers + Orders

cust_orders = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="inner"
)

cust_orders.shape

(5000, 20)

In [127]:
# Step-2 : Add Order Items

cust_orders_items = pd.merge(
    cust_orders,
    order_items,
    on="order_id",
    how="inner"
)

cust_orders_items.shape

(5000, 23)

In [129]:
# Step-3 : Add Products

final_df = pd.merge(
    cust_orders_items,
    products,
    on="product_id",
    how="inner"
)

final_df.shape

(5000, 33)

In [158]:
final_df.columns

Index(['customer_id', 'customer_name', 'email', 'phone', 'address', 'area',
       'pincode', 'registration_date', 'customer_segment', 'total_orders',
       'avg_order_value', 'order_id', 'order_date', 'promised_delivery_time',
       'actual_delivery_time', 'delivery_status', 'order_total',
       'payment_method', 'delivery_partner_id', 'store_id', 'product_id',
       'quantity', 'unit_price', 'product_name', 'category', 'brand', 'price',
       'mrp', 'margin_percentage', 'shelf_life_days', 'min_stock_level',
       'max_stock_level'],
      dtype='str')

In [157]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   customer_id             5000 non-null   int64         
 1   customer_name           5000 non-null   str           
 2   email                   5000 non-null   str           
 3   phone                   5000 non-null   str           
 4   address                 5000 non-null   str           
 5   area                    5000 non-null   str           
 6   pincode                 5000 non-null   str           
 7   registration_date       5000 non-null   datetime64[s] 
 8   customer_segment        5000 non-null   str           
 9   total_orders            5000 non-null   int64         
 10  avg_order_value         5000 non-null   float64       
 11  order_id                5000 non-null   int64         
 12  order_date              5000 non-null   object        
 13 

In [156]:
final_df.head()

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value,order_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,product_id,quantity,unit_price,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,31813,Indrajit Pau,wakeetasehgal@example.com,+911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,2024-04-10,Regular,18,1230.75,5698803942,2024-10-10,2024-10-10 13:26:15,2024-10-10 13:28:15,On Time,1227.21,UPI,38462,8304,398340,2,651.93,Instant Noodles,Instant & Frozen Food,"Nadig, Zachariah and Soni",651.93,1086.55,40.0,180,11,56
1,31813,Indrajit Pau,wakeetasehgal@example.com,+911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,2024-04-10,Regular,18,1230.75,7997347191,2024-07-11,2024-07-11 03:48:42,2024-07-11 04:01:42,Slightly Delayed,4498.83,Wallet,11517,1071,803607,3,949.73,Soap,Personal Care,"Kadakia, Mohan and Sathe",949.73,1461.12,35.0,365,21,98
2,61020,Onkar Suresh,rudradeshpande@example.com,+918421031341,"88/40, Bora Zila, Phusro-161515",Kurnool,345635,2024-07-27,New,19,1703.16,3367452972,2024-08-31,2024-08-31 14:22:08,2024-08-31 14:38:08,Significantly Delayed,2515.48,Cash,6565,4289,611575,1,482.06,Frozen Pizza,Instant & Frozen Food,"Bhat, Nigam and Hayer",482.06,803.43,40.0,180,25,87
3,61020,Onkar Suresh,rudradeshpande@example.com,+918421031341,"88/40, Bora Zila, Phusro-161515",Kurnool,345635,2024-07-27,New,19,1703.16,4283802879,2023-05-10,2023-05-10 15:37:10,2023-05-10 15:32:10,On Time,2769.12,Wallet,22353,2537,305754,1,979.99,Frozen Vegetables,Instant & Frozen Food,Mammen-Hegde,979.99,1633.32,40.0,180,22,81
4,61020,Onkar Suresh,rudradeshpande@example.com,+918421031341,"88/40, Bora Zila, Phusro-161515",Kurnool,345635,2024-07-27,New,19,1703.16,4961370923,2024-02-04,2024-02-04 16:20:26,2024-02-04 16:25:26,On Time,2560.30,Card,95563,1504,832348,2,831.43,Biscuits,Snacks & Munchies,Jani-Ram,831.43,1279.12,35.0,90,10,79


In [155]:
final_df.isnull().sum()

customer_id               0
customer_name             0
email                     0
phone                     0
address                   0
area                      0
pincode                   0
registration_date         0
customer_segment          0
total_orders              0
avg_order_value           0
order_id                  0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
product_id                0
quantity                  0
unit_price                0
product_name              0
category                  0
brand                     0
price                     0
mrp                       0
margin_percentage         0
shelf_life_days           0
min_stock_level           0
max_stock_level           0
dtype: int64

In [154]:
final_df.describe(include="number").round(2)

,customer_id,total_orders,avg_order_value,order_id,order_total,delivery_partner_id,store_id,product_id,quantity,unit_price,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
count,5000.00,5000.00,5000.00,5.000000e+03,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00
mean,50096845.22,10.48,1092.34,5.029129e+09,2201.86,50050.32,4999.69,509974.94,2.01,493.16,493.16,685.91,27.71,235.24,20.49,75.12
std,29190820.31,5.80,523.06,2.863533e+09,1303.02,28802.28,2886.09,293678.31,0.82,298.08,298.08,418.23,7.43,151.26,5.98,14.50
min,31813.00,1.00,200.43,6.046500e+04,13.25,43.00,1.00,4452.00,1.00,12.32,12.32,17.60,15.00,3.00,10.00,50.00
25%,24043135.00,6.00,614.48,2.531421e+09,1086.21,24928.50,2509.25,257719.00,1.00,227.22,227.22,326.29,20.00,90.00,15.00,64.00
50%,49978078.50,10.00,1114.50,5.074378e+09,2100.69,50262.50,4987.00,540618.00,2.00,448.16,448.16,643.82,30.00,365.00,21.00,74.00
75%,76212152.00,16.00,1546.23,7.488579e+09,3156.88,74478.25,7500.75,747801.00,3.00,781.08,781.08,1061.66,35.00,365.00,26.00,88.00
max,99893898.00,20.00,1999.83,9.998298e+09,6721.46,99968.00,9995.00,993331.00,3.00,995.98,995.98,1633.32,40.00,365.00,30.00,100.00


In [169]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   customer_id             5000 non-null   int64         
 1   customer_name           5000 non-null   str           
 2   email                   5000 non-null   str           
 3   phone                   5000 non-null   str           
 4   address                 5000 non-null   str           
 5   area                    5000 non-null   str           
 6   pincode                 5000 non-null   str           
 7   registration_date       5000 non-null   datetime64[s] 
 8   customer_segment        5000 non-null   str           
 9   total_orders            5000 non-null   int64         
 10  avg_order_value         5000 non-null   float64       
 11  order_id                5000 non-null   int64         
 12  order_date              5000 non-null   object        
 13 

In [150]:
final_df.head(1)

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,...,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level,calculated_margin
0,31813,Indrajit Pau,wakeetasehgal@example.com,+911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,2024-04-10,Regular,18,...,Instant Noodles,Instant & Frozen Food,"Nadig, Zachariah and Soni",651.93,1086.55,40.0,180,11,56,40.0


In [159]:
pd.set_option("display.max_columns", None)
final_df.head()

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value,order_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,product_id,quantity,unit_price,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,31813,Indrajit Pau,wakeetasehgal@example.com,+911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,2024-04-10,Regular,18,1230.75,5698803942,2024-10-10,2024-10-10 13:26:15,2024-10-10 13:28:15,On Time,1227.21,UPI,38462,8304,398340,2,651.93,Instant Noodles,Instant & Frozen Food,"Nadig, Zachariah and Soni",651.93,1086.55,40.0,180,11,56
1,31813,Indrajit Pau,wakeetasehgal@example.com,+911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,2024-04-10,Regular,18,1230.75,7997347191,2024-07-11,2024-07-11 03:48:42,2024-07-11 04:01:42,Slightly Delayed,4498.83,Wallet,11517,1071,803607,3,949.73,Soap,Personal Care,"Kadakia, Mohan and Sathe",949.73,1461.12,35.0,365,21,98
2,61020,Onkar Suresh,rudradeshpande@example.com,+918421031341,"88/40, Bora Zila, Phusro-161515",Kurnool,345635,2024-07-27,New,19,1703.16,3367452972,2024-08-31,2024-08-31 14:22:08,2024-08-31 14:38:08,Significantly Delayed,2515.48,Cash,6565,4289,611575,1,482.06,Frozen Pizza,Instant & Frozen Food,"Bhat, Nigam and Hayer",482.06,803.43,40.0,180,25,87
3,61020,Onkar Suresh,rudradeshpande@example.com,+918421031341,"88/40, Bora Zila, Phusro-161515",Kurnool,345635,2024-07-27,New,19,1703.16,4283802879,2023-05-10,2023-05-10 15:37:10,2023-05-10 15:32:10,On Time,2769.12,Wallet,22353,2537,305754,1,979.99,Frozen Vegetables,Instant & Frozen Food,Mammen-Hegde,979.99,1633.32,40.0,180,22,81
4,61020,Onkar Suresh,rudradeshpande@example.com,+918421031341,"88/40, Bora Zila, Phusro-161515",Kurnool,345635,2024-07-27,New,19,1703.16,4961370923,2024-02-04,2024-02-04 16:20:26,2024-02-04 16:25:26,On Time,2560.30,Card,95563,1504,832348,2,831.43,Biscuits,Snacks & Munchies,Jani-Ram,831.43,1279.12,35.0,90,10,79


In [160]:
# Revenue
final_df["revenue"] = (
    final_df["quantity"]
    * final_df["unit_price"]
).round(2)

In [161]:
# Estimated Cost Price
final_df["cost_price"] = (
    final_df["price"]
    *
    (1-final_df["margin_percentage"]/100)
).round(2)

In [162]:
final_df.head(1)

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value,order_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,product_id,quantity,unit_price,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level,revenue,cost_price
0,31813,Indrajit Pau,wakeetasehgal@example.com,+911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,2024-04-10,Regular,18,1230.75,5698803942,2024-10-10,2024-10-10 13:26:15,2024-10-10 13:28:15,On Time,1227.21,UPI,38462,8304,398340,2,651.93,Instant Noodles,Instant & Frozen Food,"Nadig, Zachariah and Soni",651.93,1086.55,40.0,180,11,56,1303.86,391.16


In [164]:
# Estimated Profit
final_df["profit"] = (
    final_df["quantity"]
    *
    (final_df["price"]- final_df["cost_price"]).round(2))

In [165]:
# Delivery Minutes

final_df["delivery_minutes"] = (

    final_df["actual_delivery_time"]
    -
    final_df["promised_delivery_time"]

).dt.total_seconds()/60

In [166]:
final_df[[
    "delivery_status",
    "delivery_minutes"
]].head()

,delivery_status,delivery_minutes
0,On Time,2.0
1,Slightly Delayed,13.0
2,Significantly Delayed,16.0
3,On Time,-5.0
4,On Time,5.0


In [167]:
final_df.head(1)

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value,order_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,product_id,quantity,unit_price,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level,revenue,cost_price,profit,delivery_minutes
0,31813,Indrajit Pau,wakeetasehgal@example.com,+911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,2024-04-10,Regular,18,1230.75,5698803942,2024-10-10,2024-10-10 13:26:15,2024-10-10 13:28:15,On Time,1227.21,UPI,38462,8304,398340,2,651.93,Instant Noodles,Instant & Frozen Food,"Nadig, Zachariah and Soni",651.93,1086.55,40.0,180,11,56,1303.86,391.16,521.54,2.0


Business Assumption: The dataset does not provide actual cost price information. Therefore, cost price and profit have been estimated using the provided margin percentage and selling price. These values represent estimated business metrics and should not be interpreted as actual accounting profit.

In [170]:
# Save as CSV

final_df.to_csv(
    "Blinkit_Final_EDA_Dataset.csv",
    index=False,
     encoding="utf-8-sig"
)

Inactive Customers extract

In [174]:
inactive_customers = customers[
    ~customers["customer_id"].isin(
        orders["customer_id"]
    )
]

inactive_customers.head()

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
1,31826,Ekiya Pau,fbedi@example.com,+919364120886,"H.No. 336\nLad Zila, Hajipur-409871",Chinsurah,201602,2023-11-29,New,18,752.78
3,75482,Jeet Gandhi,amrita05@example.net,+916683687947,"95/861, Jaggi, Sikar-343285",Korba,298093,2024-09-19,Regular,13,1938.38
19,894128,Chatura Agarwal,harishom@example.net,+919523503339,58/69\nMallick Path\nRajahmundry 318453,Durgapur,013150,2023-07-20,Inactive,5,1323.32
24,1060685,Yadavi Rajagopalan,dipta24@example.net,+912609155283,"48\nChoudhary Ganj, Gorakhpur 965066",Mango,449803,2024-03-07,Inactive,4,999.24
26,1134585,Bhavani Rau,uppalvrishti@example.com,+913705629591,"61, Mitra Zila, Bhatpara-234618",Ghaziabad,553914,2024-02-06,Regular,8,1975.21


In [175]:
inactive_customers["customer_id"].nunique()

328

In [176]:
##Active Customers
active_customers = customers[
    customers["customer_id"].isin(
        orders["customer_id"]
    )
]

active_customers["customer_id"].nunique()

2172

In [177]:
inactive_percentage = round(

    (inactive_customers["customer_id"].nunique()
    /
    customers["customer_id"].nunique())

    *100,2

)

inactive_percentage

13.12

The Customers table contains 2,500 registered customers, whereas only 2,172 unique customers are present in the Orders table. This indicates that 328 customers did not place any orders during the analysis period. Since the final analytical dataset was created using order-related tables, it includes only active customers who generated transactions.

In [ ]:
Total Registered Customers = 2500
Active Customers = 2172
Inactive Customers = 328
Inactive Customer Percentage = 13.12%