SELECT *
INTO ORDERS
FROM BLINKIT_ORDERS;

SELECT *
INTO ORDER_ITEMS
FROM BLINKIT_ORDER_ITEMS;

SELECT *
INTO PRODUCTS
FROM BLINKIT_PRODUCTS;

SELECT *
INTO CUSTOMERS
FROM BLINKIT_CUSTOMERS;

---VERIFY ROW COUNTS
SELECT COUNT(*) AS TOTAL_ROWS--2500rows
FROM CUSTOMERS;


SELECT COUNT(*) AS TOTAL_ROWS
FROM ORDERS;--5000rows


SELECT COUNT(*) AS TOTAL_ROWS
FROM ORDER_ITEMS;--5000rows


SELECT COUNT(*) AS TOTAL_ROWS
FROM PRODUCTS;--268rows
---validation all data 
select top 10 * from customers
select top 10 * from orders
select top 10 * from ORDER_ITEMS
select top 10 * from PRODUCTS

